# Generated by Django 5.0.6 on 2024-06-01 23:47

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('Eventbookingapp', '0002_booking_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='setup_time',
            field=models.TimeField(default=datetime.time(9,0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
