# Generated by Django 5.0.6 on 2024-06-01 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventbookingapp', '0003_booking_setup_time_alter_booking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='setup_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
