# Generated by Django 5.0.6 on 2024-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventbookingapp', '0004_alter_booking_setup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
